# Generated by Django 3.2.6 on 2022-02-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20220227_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_post',
            field=models.ManyToManyField(blank=True, related_name='post_like', to='blogs.IpModel'),
        ),
    ]
