# Generated by Django 3.2.6 on 2022-02-27 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0004_auto_20220228_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='parent',
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_content', to='blogs.post'),
        ),
        migrations.CreateModel(
            name='ReplayComment',
            fields=[
                ('rno', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('parrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blogcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
